blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/Kishor5115/TPU8x8/discussions
    about: Ask questions or discuss ideas about the TPU design and flow here.
